name: verify-main

on:
  push:
    branches:
    - main

jobs:
  call-verify:
    uses: Joe75792433/cp-library/.github/workflows/verify.yml@main
    with:
      verify_subcommand: all
    secrets: inherit